### ISSUE TITLE
HTML file not found

### ISSUE THREAD

**Issue by fjchen7** [Zeioth/dooku.nvim#1]
I run `:DookuGenerate` in my rust file and it seems not working

![image](https://github.com/Zeioth/dooku.nvim/assets/10106636/f57a70d9-b695-4cff-a698-3aa11270eddf)

chealthcheck
![image](https://github.com/Zeioth/dooku.nvim/assets/10106636/d16a6291-80b0-4747-a8d5-34a590dc68b0)

dooku version: latest([0f7b500](https://github.com/Zeioth/dooku.nvim/commit/0f7b5004f0e5d93bd15afa0db52897318b18109f))

**Comment by Zeioth** [comment]
Hello @jimzk, ok it seems you are trying to use it for rust. Make sure.

* You have a .git directory on your project root directory. So the plugin can detect your root directory.  You can configure that with the `project_root` you can find on the readme.
* You must either run `DookuGenerate` and then `DookuOpen`, or just run `DookuGenerate` two times, if you have the option `on_generate_open` enabled.

I hope that helps.

**Comment by fjchen7** [comment]
Hi @Zeioth Thank for reply.

The issue happens when I run `DookuGenerate` in a git project. My `pwd` prints git root path. I am not sure what goes wrong.

Also, I does not have custom configuration, just using the default.

**Comment by Zeioth** [comment]
@jimzk It should work now.

## More info
We had indeed a bug [here](https://github.com/Zeioth/dooku.nvim/blob/0f7b5004f0e5d93bd15afa0db52897318b18109f/lua/dooku/backends/rustdoc.lua#L26). `uv.spawn()` fails the entire command when one of the arguments is `""`, instead of ignoring it. So we now convert all `""` config options to `nil` at startup.

Thank you so much for reporting. Please let me know if for some reason you still experience it.
